### ISSUE TITLE
InternalOAuthError: failed to fetch user profile (new Community Management API of LinkedIn)

### ISSUE THREAD

**Issue by jitendrakumar025** [auth0/passport-linkedin-oauth2#102]
InternalOAuthError: failed to fetch user profile
    at Strategy.<anonymous> (C:\VsCode\OfficeINK\OfficeInk-api\node_modules\passport-linkedin-oauth2\lib\oauth2.js:57:19)
    at passBackControl (C:\VsCode\OfficeINK\OfficeInk-api\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\VsCode\OfficeINK\OfficeInk-api\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    
    
I have been stuck in this error for 1 week, I googled about this error but couldn't get an updated solution according to new Community Management API of LinkedIn, Please help me @jamescgarrett .

The following is  Passport   linkedinStrategy configuration :

`require('dotenv').config();
const LinkedInStrategy = require("passport-linkedin-oauth2").Strategy;
const passport = require("passport");

passport.serializeUser((user, done) => {
    done(null, user);
  });
  
  passport.use(
    new LinkedInStrategy(
      {
        clientID: process.env.LINKEDIN_CLIENT_ID,
        clientSecret: process.env.LINKEDIN_CLIENT_SECRET,
        callbackURL: 'http://localhost:5000/auth/linkedin/callback',
        scope: ['openid', 'profile', 'email'],
        state: true,

      },
      async (accessToken, refreshToken, done) => {
        try {
          const userInfo = await linkedin.getProfile(
            process.env.LINKEDIN_CLIENT_ID,
            process.env.LINKEDIN_CLIENT_SECRET,
            accessToken
          );
  
          console.log(userInfo)
          done(null, userInfo);
        } catch (err) {
          console.log(err)
          done(err, false);
        }
      }
    )
  );

passport.deserializeUser((user, done) => {
    done(null, user);
});`

server running on localhost:5000,

Please help me, Its a lot to me.
Thanks ,

**Comment by ErcilioMarques** [comment]
facing same issue, seems like the new major change on linkedin API break everything. and the their current doc its not clear

**Comment by herquiloidehele** [comment]
Having the same problem here

**Comment by angelhodar** [comment]
@ErcilioMarques @herquiloidehele Do you guys have the problem just with the basic readme config? I dont understand why it fails because this library has been updated just a month ago to use the new OpenID API from linkedin

**Comment by jamescgarrett** [comment]
Hey all, apologies for the issues you are running into. As you are aware LinkedIn has deprecated `Sign In with LinkedIn` and is now enforcing new apps to use `Sign In with LinkedIn using OpenID Connect`. We've made the necessary changes to this repo supporting this change, but have not yet published the changes to `npm`. We are working on getting newer versions published in `npm`, but for now you should be able to install the updates using 
`npm install github:auth0/passport-linkedin-oauth2`
or
`npm install github:auth0/passport-linkedin-oauth2#v3.0.0`

**Comment by vilasshetkar** [comment]
Hi @jamescgarrett,
I've thoroughly investigated this issue and implemented a fix in the [Community Management API Fix PR](https://github.com/auth0/passport-linkedin-oauth2/pull/103). I've tested the solution, and it resolves the issue. Kindly review and merge this PR at your earliest convenience to close the problem.

Thanks!

**Comment by GodoyMS** [comment]
Hi,
Adding a new field 'openid' on the  scope array worked for me 

`new LinkedinStrategy({
         clientID: config.OAUTH2_ID_CLIENT_LINKEDIN!,
         clientSecret: config.OAUTH2_SECRET_LINKEDIN!,
         callbackURL: http://localhost:5000/auth/linkedin/callback,
         scope: ['email', 'profile','openid'],
       }`

**Comment by NabilSaikaly** [comment]
@GodoyMS 
Hello, did you add the scope as well in the route?
ex: `router.get('/linkedin', passport.authenticate('linkedin', { scope: ['openid', 'profile','email'] }));`
Or just in the strategy?

Because both are not working for me, and i'm still having the error: 
`InternalOAuthError: failed to fetch user profile`

**Comment by NabilSaikaly** [comment]
Hello @jamescgarrett 😄 

Hope all is going well.

Will the newer versions be published to npm?

**Comment by pedroresende** [comment]
@jamescgarrett why not publish this to npm ?

**Comment by sakshiarora386** [comment]
plz do publish this to npm, to avoid these issues
