### ISSUE TITLE
InternalOAuthError: failed to fetch user profile

### ISSUE THREAD

**Issue by hadyrashwan** [auth0/passport-linkedin-oauth2#57]
Is this error related to my application or from LinkedIn side ??
```
InternalOAuthError: failed to fetch user profile
    at /user_code/node_modules/passport-linkedin-oauth2/lib/oauth2.js:29:28
    at passBackControl (/user_code/node_modules/passport-linkedin-oauth2/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/user_code/node_modules/passport-linkedin-oauth2/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9
```

**Comment by ahmdsolmn** [comment]
https://github.com/auth0/passport-linkedin-oauth2/issues/24#issuecomment-358151910
