### ISSUE TITLE
TokenError: Client authentication failed

### ISSUE THREAD

**Issue by tjstalcup** [auth0/passport-linkedin-oauth2#64]
Routes:
` app.get('/auth/linkedin', passport.authenticate('linkedin'));

  app.get('/auth/linkedin/callback', passport.authenticate('linkedin', { 
      successRedirect: '/profile',
      failureRedirect: '/' 
  }));`

Strategy:
`passport.use(new LinkedInStrategy({
        clientID: "XXXXX",
        clientSecret: "XXXX",
        callbackURL: "http://localhost:8080/auth/linkedin/callback",
        scope: ['r_emailaddress', 'r_basicprofile'],
        state: true
      }, function(accessToken, refreshToken, profile, done) {
        console.log('profile---',profile);
        User.findOrCreate({ linkedinId: profile.id }, function (err, user) {
          return done(err, user);
        });
      }
    ));`

I'm not seeing the console.log just the following error message:

`TokenError: Client authentication failed
    at Strategy.OAuth2Strategy.parseErrorResponse (/Users/tjstalcup/Sites/devjobs/node_modules/passport-oauth2/lib/strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (/Users/tjstalcup/Sites/devjobs/node_modules/passport-oauth2/lib/strategy.js:376:16)
    at /Users/tjstalcup/Sites/devjobs/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /Users/tjstalcup/Sites/devjobs/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/tjstalcup/Sites/devjobs/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/tjstalcup/Sites/devjobs/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)`

**Comment by ShweYeeMyaWin** [comment]
I am facing the same problem as well. Any suggestion about this issue ?

**Comment by catrawalkar** [comment]
Did you find a solution to this? I still not able to pass through it. Please help

**Comment by CajetanRodrigues** [comment]
Im also stuck

**Comment by YuraGB** [comment]
The question was asked from January 2019 and the issue appears and appears.....

**Comment by colburnrose** [comment]
Go to the Products tab and add Sign in with Linkedin, which allows you to sign in with your professional identity.

https://stackoverflow.com/questions/53479131/unauthorized-scope-error-in-linkedin-oauth2-authentication

<img width="775" alt="linkedin" src="https://user-images.githubusercontent.com/42094680/97096404-9a64e480-1620-11eb-848b-cd47219c196a.png">
![Screen Shot 2020-10-24 at 7 14 17 PM](https://user-images.githubusercontent.com/42094680/97096417-dc8e2600-1620-11eb-8f76-0a822494caf7.png)
