### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by mimrank** [auth0/passport-linkedin-oauth2#73]
it's not work with latest APIs

`{ InternalOAuthError: failed to fetch user profile
    at G:\nodeproject\ufoneGamifiedRecruitment\node_modules\passport-linkedin-oauth2\lib\oauth2.js:30:28
    at passBackControl (G:\nodeproject\ufoneGamifiedRecruitment\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (G:\nodeproject\ufoneGamifiedRecruitment\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1132:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
  name: 'InternalOAuthError',
  message: 'failed to fetch user profile'`

**Comment by BrunildaNinox** [comment]
https://www.npmjs.com/package/@sokratis/passport-linkedin-oauth2 updated for the v2 APIs. hope it helps :)
