### ISSUE TITLE
[Unhandled error]AuthorizationError: The user cancelled the authorization

### ISSUE THREAD

**Issue by kunalk16** [auth0/passport-linkedin-oauth2#90]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.
When the user logs in but denies to give permission to the app to access linkedin data, there is an unhandled error thrown that causes a 500.
![image](https://user-images.githubusercontent.com/5303824/188679009-ee8cb5b8-80e9-4ec3-8628-cdc0df2d12f9.png)
Stacktrace:
   at LinkedinAuthStrategy.OAuth2Strategy.authenticate (C:\a\b\node_modules\passport-oauth2\lib\strategy.js:138:25)
    at attempt (C:\a\b\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (C:\a\b\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at C:\a\b\node_modules\@nestjs\passport\dist\auth.guard.js:96:3
    at new Promise (<anonymous>)
    at C:\a\b\design-platform-backend\node_modules\@nestjs\passport\dist\auth.guard.js:88:83
    at MixinAuthGuard.<anonymous> (C:\a\b\node_modules\@nestjs\passport\dist\auth.guard.js:49:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\a\b\node_modules\@nestjs\passport\dist\auth.guard.js:17:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
It can be reproduced consistently.
1. Login to linkedin
2. Instead of allowing permission, press cancel
![image](https://user-images.githubusercontent.com/5303824/188680539-63a4fd13-51b4-4caa-b488-7faa562f176a.png)
3. We get a 500 with the stacktrace:
   at LinkedinAuthStrategy.OAuth2Strategy.authenticate (C:\a\b\node_modules\passport-oauth2\lib\strategy.js:138:25)
    at attempt (C:\a\b\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (C:\a\b\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at C:\a\b\node_modules\@nestjs\passport\dist\auth.guard.js:96:3
    at new Promise (<anonymous>)
    at C:\a\b\design-platform-backend\node_modules\@nestjs\passport\dist\auth.guard.js:88:83
    at MixinAuthGuard.<anonymous> (C:\a\b\node_modules\@nestjs\passport\dist\auth.guard.js:49:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\a\b\node_modules\@nestjs\passport\dist\auth.guard.js:17:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Environment

> Please provide the following:

- **Version of this library used:**2.0.0
- **Version of the platform or framework used, if applicable:**NestJS with typescript
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

Strategy code:
```
@Injectable()
export class LinkedinAuthStrategy extends PassportStrategy(Strategy, 'linkedin') {
    constructor() {
        super({
            clientID: '<clientID>',
            clientSecret: <secret>,
            callbackURL: <url>,
            scope: ['r_emailaddress', 'r_liteprofile'],
        });
    }

    validate(accessToken: string, refreshToken: string, profile: Profile, done: Function): void {
        const { name, emails, photos } = profile;
        const user = {
            email: emails[0]?.value,
            firstName: name.givenName,
            lastName: name.familyName,
            picture: photos[0]?.value,
        };

        done(null, user);
    }
}
```

**Comment by RedRosh** [comment]
For anyone facing this error, you can handle it in NestJs by adding a filter on top of the controller function:

```typescript
@Get("linkedin/callback")
@UseGuards(LinkedinAuthGuard)
@UseFilters(new UnauthorizedFilter()) // <--- HERE
linkedinCallback(@LoggedUser() user: User, @Res() res: Response) {

    const clientUrl = ".....";
    res.redirect(clientUrl);
}
```

to implement the filter:

```typescript
    @Catch(UnauthorizedException)
export class UnauthorizedFilter implements ExceptionFilter {
    catch(exception: HttpException, host: ArgumentsHost) {
        const ctx = host.switchToHttp();
        const response = ctx.getResponse<Response>();

        // Get the error message from the exception if available
        const errorMessage = exception?.message || "Unauthorized";

        // Do something with the error
        response.redirect(CLIENT_URL);
    }
}

```
